[paths]
input_path = "/Users/clem/Desktop/EEBOTest3/eng"
output_path = "/Users/clem/Desktop/EEBOTest3/output"

[logging]
level = "verbose"  # select between "minimal", "verbose", or "statistic"

[settings]
context_size = 20
debug_mode = true

[unicode_replacements]
replacements_on = false # or false
characters_to_delete = ["\u00B6", "\u261E", "\u2740", "\u2767"]
characters_to_replace = {"Ʋ" = "U", "&c." = "etc.", "ꝑ" = "per", "ꝭ" = "s", "ȝ" = "g"}
