[directories]
working_directory = "users/name/directory" # working directory path

[logging] # don't change, still shaky
level = "minimal"  # or "verbose" or "statistic"

[settings]
context_size = 20

[unicode_replacements]
"\u00B6" = ""  # empty "" is a deletion
"\u261E" = ""
"\u2740" = ""
"\u2767" = ""
"Ʋ" = "U"
"&c." = "etc."
"ꝑ" = "per"
"ꝭ" = "s"
"ȝ" = "g"
